# Generated by Django 3.1.7 on 2021-03-18 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='answercategory',
            options={'verbose_name_plural': 'Answer Categories'},
        ),
        migrations.AlterModelOptions(
            name='answercategorynode',
            options={'verbose_name_plural': 'Answer Category Nodes'},
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'categories'},
        ),
        migrations.AddField(
            model_name='post',
            name='categories',
            field=models.ManyToManyField(to='app.Category'),
        ),
    ]
