# Generated by Django 3.1.7 on 2021-03-19 19:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_post_visits'),
    ]

    operations = [
        migrations.AddField(
            model_name='answercategory',
            name='post',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='reviewed_categories', to='app.post'),
            preserve_default=False,
        ),
    ]
