# Generated by Django 3.1.7 on 2021-03-21 09:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_answercategory_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='is_top_answer',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='answercategory',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviewed_categories', to='app.category'),
        ),
    ]
