# Generated by Django 3.1.7 on 2021-03-21 10:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20210321_1047'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='has_top_answer',
        ),
    ]
