# Generated by Django 3.1.7 on 2021-03-21 14:38

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_remove_post_has_top_answer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answercategory',
            name='rank',
            field=models.IntegerField(validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(1)]),
        ),
    ]
